### ISSUE TITLE
Bug in RemoteMediaStorage

### ISSUE THREAD

**Issue by peec** [netgen/NetgenRemoteMediaBundle#18]
Using v. 1.0.10-alpha,

Getting Exception when importing cloudinary resources with custom script.

This line:

https://github.com/netgen/NetgenRemoteMediaBundle/blob/781c484f2756b6616e817cfe2248823ab5dfb65d/Core/FieldType/RemoteMedia/RemoteMediaStorage.php#L153

I think this line should be 

```
if (!$gateway->remoteResourceConnected($resourceId, $this->provider->getIdentifier())) {
```

**Comment by iherak** [comment]
Note to self: fixed in `dev` branch (https://github.com/netgen/NetgenRemoteMediaBundle/commit/5578b9f6972ab147f45640076107a529faef341d#diff-173f564a8662d010aa711892a2977d22), which is to become 1.0

The fix should be backported to master and tagged with new minor alpha version.

**Comment by iherak** [comment]
Fixed in master https://github.com/netgen/NetgenRemoteMediaBundle/blob/master/Core/FieldType/RemoteMedia/RemoteMediaStorage.php#L156.

Thanks for bringing this to our attention @peec!
