### ISSUE TITLE
Any reason versions >= 1.1.9 are not supporting ezsystems/ezpublish-kernel 7.x ?

### ISSUE THREAD

**Issue by beery** [netgen/NetgenRemoteMediaBundle#33]
Since commit https://github.com/netgen/NetgenRemoteMediaBundle/commit/ac6d7e103508231704db8ae5652deb6d93b0fa16

**Comment by iherak** [comment]
ezsystems/ezpublish-kernel 7.x  was never officially supported, as it was released after initial (1.1) version of this bundle has been released.

Next version of NGRM will probably be 2.0, and we will add support for 7.x, and at the same time drop support for eZ 5.4.x (basically we won't support anything under 6.0).

If it's crucial for you, we can try and test this with 7.x kernel, and possibly support that as well, if there are no breaking changes compared to kernel 6. If there are, we will not make any more adjustments in 1.x version of this bundle, as it is already complicated to support 5.4 and 6 at the same time.

**Comment by beery** [comment]
Not crucial for me. Was adding it to the new Kverneland installation, and maybe that would be the right place to test it against 7.x.
