### ISSUE TITLE
RemoteMediaSettings is not defined in ezxmltext wysiwyg

### ISSUE THREAD

**Issue by SalvatorePollaci** [netgen/NetgenRemoteMediaBundle#42]
I'm using the Legacy Bridge with Netgen Admin Ui. I have an 'ezxmltext' attribute, but when I click on the blue cloud icon to attempt to open the NgRemoteMedia modal,I get the following javascript error:
```
ReferenceError: RemoteMediaSettings is not defined
```

Is this a bug or have I forgotten to configure something?

**Comment by einfoadm** [comment]
I'm having the same issue! Is there any workaround?

**Comment by SalvatorePollaci** [comment]
@iherak Any updates on this issue? Thanks

**Comment by iherak** [comment]
@SalvatorePollaci @einfoadm could you please test https://github.com/netgen/NetgenRemoteMediaBundle/pull/47 and see if it works?

One known issue persists: this fix will *not* read translation files, all labels will be in english, hope that is ok for now. We will try to improve this in the future, hopefully soon..

**Comment by SalvatorePollaci** [comment]
@iherak I can confirm that the following commit is working: https://github.com/netgen/NetgenRemoteMediaBundle/commit/8b6651060414c13abbcda2f4693d2d66f0a53651

Thanks!

**Comment by iherak** [comment]
@SalvatorePollaci @einfoadm fixed in https://github.com/netgen/NetgenRemoteMediaBundle/releases/tag/1.1.16

Also fixed in master.
