### ISSUE TITLE
Image scalling in backend uses HTTP instead of HTTPS

### ISSUE THREAD

**Issue by RandyCupic** [netgen/NetgenRemoteMediaBundle#46]
In `1.1` release (and probably in `master` as well), on `Scale` functionality, HTTP is being used to load images instead of HTTPS. The problem probably lays in the fact that `url` attribute is being used from Cloudinary resource, instead of `secure_url`.

**Comment by iherak** [comment]
Fixed both on 1.1-release (with new tag - 1.1.17) and master
