### ISSUE TITLE
"Alternate text" field does not show persisted value

### ISSUE THREAD

**Issue by SalvatorePollaci** [netgen/NetgenRemoteMediaBundle#48]
If the 'Alternative text' field of a ngremotemedia attribute is inserted by an editor, such value correctly gets persisted to db, but when the content object gets re-edited, such value is always empty.

**Steps to reproduce:**
1)Create a content object which contains a ngremotemedia attribute
2)Insert an image and populate the 'Alternative text' field
3)Publish the content object
4)Verify that the content object's ngremotemedia attribute contains the inserted 'Alternative text' field value
5)Re-edit the content object
6)Observe that the 'Alternative text' field is empty

**Comment by iherak** [comment]
Hi, just to confirm, this happens on master, right?

**Comment by SalvatorePollaci** [comment]
Oh yes sorry, I'm currently on master branch commit `9a5177c`

**Comment by iherak** [comment]
I've confirmed the issue and submitted the PR with the fix for 1.1-release. Still waiting for travis to finish, so if all goes well (it should), I'll merge to 1.1, tag it, and merge it back to master as well.
Will notify here once it's all done.

**Comment by iherak** [comment]
Fixed both on 1.1-release (with new tag - 1.1.17) and master

**Comment by SalvatorePollaci** [comment]
Thank you very much
