### ISSUE TITLE
Content issue with eZ Platform 2.5.

### ISSUE THREAD

**Issue by jfauske** [netgen/NetgenRemoteMediaBundle#54]
On curent master we get
`[ Oct 28 2019 12:32:33 ] Unexpected error, the message was : Argument 1 passed to Netgen\Bundle\RemoteMediaBundle\Templating\Twig\Extension\NetgenRemoteMediaExtension::getRemoteImageVariation() must be an instance of eZ\Publish\Core\Repository\Values\Content\Content, instance of eZ\Publish\Core\Repository\Values\Content\ContentProxy given, called in /var/www/ezpublish/cache/site/dev/twig/50/50a6355a88ca3f1d5597fb0096961a07c39f3542182d5cc1a4ee428306d2f61a.php on line 176 in /var/www/vendor/netgen/remote-media-bundle/bundle/Templating/Twig/Extension/NetgenRemoteMediaExtension.php on line 108`

**Comment by iherak** [comment]
Fixed by https://github.com/netgen/NetgenRemoteMediaBundle/pull/55
